from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime

import numpy as np
import pandas as pd

from tradingbot.core.enums import (
    OrderSide,
    OrderStatus,
    OrderType,
    PositionSide,
    SignalType,
)


@dataclass(frozen=True)
class Candle:
    """Single OHLCV candle."""

    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: float

    def to_dict(self) -> dict:
        return {
            "timestamp": self.timestamp,
            "open": self.open,
            "high": self.high,
            "low": self.low,
            "close": self.close,
            "volume": self.volume,
        }


def candles_to_dataframe(candles: list[Candle]) -> pd.DataFrame:
    """Convert list of Candle objects to a pandas DataFrame."""
    if not candles:
        return pd.DataFrame(columns=["timestamp", "open", "high", "low", "close", "volume"])
    df = pd.DataFrame([c.to_dict() for c in candles])
    df["timestamp"] = pd.to_datetime(df["timestamp"])
    df = df.set_index("timestamp")
    return df


def dataframe_to_candles(df: pd.DataFrame) -> list[Candle]:
    """Convert a pandas DataFrame back to list of Candle objects."""
    candles = []
    for ts, row in df.iterrows():
        candles.append(
            Candle(
                timestamp=ts.to_pydatetime() if isinstance(ts, pd.Timestamp) else ts,
                open=float(row["open"]),
                high=float(row["high"]),
                low=float(row["low"]),
                close=float(row["close"]),
                volume=float(row["volume"]),
            )
        )
    return candles


@dataclass(frozen=True)
class Signal:
    """Trading signal generated by a strategy."""

    timestamp: datetime
    symbol: str
    signal_type: SignalType
    price: float
    strength: float = 1.0  # 0.0 ~ 1.0, used for position sizing


@dataclass
class Order:
    """Represents a trading order."""

    id: str
    symbol: str
    side: OrderSide
    order_type: OrderType
    quantity: float
    price: float | None = None  # None for market orders
    status: OrderStatus = OrderStatus.PENDING
    created_at: datetime | None = None
    filled_at: datetime | None = None
    filled_price: float | None = None
    fee: float = 0.0


@dataclass
class Trade:
    """A completed round-trip trade (entry + exit)."""

    symbol: str
    entry_order: Order
    exit_order: Order

    @property
    def _trade_quantity(self) -> float:
        """Actual traded quantity — min of entry/exit to handle partial fills safely."""
        return min(self.entry_order.quantity, self.exit_order.quantity)

    @property
    def pnl(self) -> float:
        """Profit/loss including fees."""
        assert self.entry_order.filled_price is not None
        assert self.exit_order.filled_price is not None
        qty = self._trade_quantity
        gross = (self.exit_order.filled_price - self.entry_order.filled_price) * qty
        return gross - self.entry_order.fee - self.exit_order.fee

    @property
    def pnl_pct(self) -> float:
        """Profit/loss as percentage of entry value."""
        assert self.entry_order.filled_price is not None
        qty = self._trade_quantity
        entry_value = self.entry_order.filled_price * qty
        if entry_value == 0:
            return 0.0
        return self.pnl / entry_value

    @property
    def duration(self) -> float | None:
        """Trade duration in hours."""
        if self.entry_order.filled_at and self.exit_order.filled_at:
            delta = self.exit_order.filled_at - self.entry_order.filled_at
            return delta.total_seconds() / 3600
        return None

    @property
    def is_win(self) -> bool:
        return self.pnl > 0


@dataclass
class Position:
    """An open position."""

    symbol: str
    side: PositionSide
    size: float  # quantity of asset
    entry_price: float
    entry_time: datetime
    stop_loss: float | None = None
    take_profit: float | None = None

    @property
    def entry_value(self) -> float:
        return self.entry_price * self.size

    def unrealized_pnl(self, current_price: float) -> float:
        if self.side == PositionSide.LONG:
            return (current_price - self.entry_price) * self.size
        return 0.0

    def unrealized_pnl_pct(self, current_price: float) -> float:
        if self.entry_value == 0:
            return 0.0
        return self.unrealized_pnl(current_price) / self.entry_value


@dataclass
class PortfolioState:
    """Snapshot of portfolio at a point in time."""

    timestamp: datetime
    cash: float
    positions: list[Position] = field(default_factory=list)

    @property
    def total_position_value(self) -> float:
        return sum(p.entry_value for p in self.positions)

    def equity(self, prices: dict[str, float]) -> float:
        """Total equity = cash + sum of position values at current prices."""
        position_value = sum(
            prices.get(p.symbol, p.entry_price) * p.size for p in self.positions
        )
        return self.cash + position_value
